### ISSUE TITLE
Deadlock with OpenMP offloading and TCMalloc

### ISSUE THREAD

**Issue by Maetveis** [RadeonOpenCompute/ROCR-Runtime#151]
# Short description

Running an openmp enabled application linking to a shared library with OpenMP offloading while using TCMalloc will
result in a deadlock in the rocr runtime.

# Steps to reproduce
## Environment

<details>
<summary>Ubuntu 20.04</summary>

```console
❯ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

</details>

<details>
<summary>ROCr version</summary>

```console
❯ dpkg -s hsa-rocr | grep Version
Version: 1.7.0.50400-72~20.04
```

</details>

<details>
<summary>clang/libomp version</summary>

```console
❯ clang --version
clang version 16.0.0 (git@github.com:llvm/llvm-project.git 9534762af54ad6ac125afd8cbebdf45f669e16f2)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin
```

</details>

<details>
<summary>TCMalloc version</summary>

TCmalloc is installed from the unbuntu repositories via `apt-get install libtcmalloc-minimal4`

```console
❯ dpkg -s libtcmalloc-minimal4 | grep Version
Version: 2.7-1ubuntu2
```

</details>

As a threading related deadlock, this error seems to be pretty sensitive to the environment. I have tried with different distributions of llvm:
- LLVM upstream (at commit ebfb1ddbe18457723ea62f4ecc94667a44ca4569) -> can reproduce
- LLVM from ROCM 5.4.1 -> can reproduce
- AOMP 16.0-3 -> failed to reproduce
- AOMP 15.0-3 -> failed to reproduce 

## Reproducer

The following commands reproduce the problem with a high frequency (but not always as this is timing sensitive!)

```console
touch empty.c
echo "int main(){}" > main.c
clang -fPIC -fopenmp -fopenmp-targets=amdgcn-amd-amdhsa -Xopenmp-target=amdgcn-amd-amdhsa -march=gfx90a empty.c -shared -o liba.so
clang main.c liba.so
LD_LIBRARY_PATH=. LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libtcmalloc_minimal.so.4" ./a.out
```

# Observed behavior

The application hangs forever.

# Expected behavior

It does not hang.

# Details

I have captured the following backtrace at the time of the hang:
<details>
<summary>GDB backtrace</summary>

```plaintext
Thread 1 "a.out" received signal SIGINT, Interrupt.
__lll_lock_wait (futex=futex@entry=0x555555d83dd0, private=0) at lowlevellock.c:52
52      lowlevellock.c: No such file or directory.
(gdb) bt
#0  __lll_lock_wait (futex=futex@entry=0x555555d83dd0, private=0) at lowlevellock.c:52
#1  0x00007ffff77050a3 in __GI___pthread_mutex_lock (mutex=0x555555d83dd0) at ../nptl/pthread_mutex_lock.c:80
#2  0x00007ffff7264809 in rocr::os::AcquireMutex (lock=0x555555d83dd0) at /workspaces/deps/ROCR-Runtime-rocm-5.4.1/src/core/util/lnx/os_linux.cpp:247
#3  0x00007ffff72a48f6 in rocr::KernelMutex::Acquire (this=0x555555dfe308) at /workspaces/deps/ROCR-Runtime-rocm-5.4.1/src/core/util/locks.h:63
#4  rocr::ScopedAcquire<rocr::KernelMutex>::container<rocr::KernelMutex, true>::Acquire (this=0x7fffffffd7d8) at /workspaces/deps/ROCR-Runtime-rocm-5.4.1/src/core/util/locks.h:208
#5  rocr::ScopedAcquire<rocr::KernelMutex>::ScopedAcquire (this=0x7fffffffd7d8, lock=0x555555dfe308) at /workspaces/deps/ROCR-Runtime-rocm-5.4.1/src/core/util/locks.h:185
#6  rocr::core::Runtime::SetAsyncSignalHandler (this=0x555555dfe000, signal=..., cond=HSA_SIGNAL_CONDITION_NE, value=0, handler=0x7ffff727e2b0 <rocr::AMD::AqlQueue::DynamicScratchHandler<false>(long, void*)>, arg=0x555555ddc840) at /workspaces/deps/ROCR-Runtime-rocm-5.4.1/src/core/runtime/runtime.cpp:666
#7  0x00007ffff7294870 in rocr::AMD::hsa_amd_signal_async_handler (hsa_signal=..., cond=cond@entry=HSA_SIGNAL_CONDITION_NE, value=value@entry=0, handler=0x7ffff727e2b0 <rocr::AMD::AqlQueue::DynamicScratchHandler<false>(long, void*)>, arg=arg@entry=0x555555ddc840) at /workspaces/deps/ROCR-Runtime-rocm-5.4.1/src/core/runtime/hsa_ext_amd.cpp:528
#8  0x00007ffff727bce3 in rocr::AMD::AqlQueue::AqlQueue (this=0x555555ddc840, agent=<optimized out>, req_size_pkts=<optimized out>, node_id=2, scratch=..., callback=<optimized out>, err_data=0x0, is_kv=<optimized out>) at /workspaces/deps/ROCR-Runtime-rocm-5.4.1/src/core/runtime/amd_aql_queue.cpp:293
#9  0x00007ffff7276b9b in rocr::AMD::GpuAgent::QueueCreate (this=0x555555e0d400, size=4096, queue_type=<optimized out>, event_callback=0x7ffff74a7350 <callbackQueue(hsa_status_t, hsa_queue_s*, void*)>, data=0x0, private_segment_size=<optimized out>, group_segment_size=<optimized out>, queue=0x7fffffffd9b8) at /workspaces/deps/ROCR-Runtime-rocm-5.4.1/src/core/runtime/amd_gpu_agent.cpp:1186
#10 0x00007ffff728a683 in rocr::HSA::hsa_queue_create (agent_handle=..., size=4096, type=0, callback=<optimized out>, data=0x0, private_segment_size=4294967295, group_segment_size=4294967295, queue=0x7fffffffda60) at /workspaces/deps/ROCR-Runtime-rocm-5.4.1/src/core/runtime/hsa.cpp:717
#11 0x00007ffff74b20af in RTLDeviceInfoTy::RTLDeviceInfoTy() () from /usr/local/lib/libomptarget.rtl.amdgpu.so
#12 0x00007ffff748b4b0 in _GLOBAL__sub_I_rtl.cpp () from /usr/local/lib/libomptarget.rtl.amdgpu.so
#13 0x00007ffff7fe0b9a in call_init (l=<optimized out>, argc=argc@entry=1, argv=argv@entry=0x7fffffffe488, env=env@entry=0x7fffffffe498) at dl-init.c:72
#14 0x00007ffff7fe0ca1 in call_init (env=0x7fffffffe498, argv=0x7fffffffe488, argc=1, l=<optimized out>) at dl-init.c:30
#15 _dl_init (main_map=0x555555d77900, argc=1, argv=0x7fffffffe488, env=0x7fffffffe498) at dl-init.c:119
#16 0x00007ffff7d48985 in __GI__dl_catch_exception (exception=<optimized out>, operate=<optimized out>, args=<optimized out>) at dl-error-skeleton.c:182
#17 0x00007ffff7fe543d in dl_open_worker (a=a@entry=0x7fffffffdf50) at dl-open.c:758
#18 0x00007ffff7d48928 in __GI__dl_catch_exception (exception=<optimized out>, operate=<optimized out>, args=<optimized out>) at dl-error-skeleton.c:208
#19 0x00007ffff7fe460a in _dl_open (file=0x555555d82cc0 "libomptarget.rtl.amdgpu.so", mode=-2147483391, caller_dlopen=<optimized out>, nsid=-2, argc=1, argv=0x7fffffffe488, env=0x7fffffffe498) at dl-open.c:837
#20 0x00007ffff76eb34c in dlopen_doit (a=a@entry=0x7fffffffe170) at dlopen.c:66
#21 0x00007ffff7d48928 in __GI__dl_catch_exception (exception=exception@entry=0x7fffffffe110, operate=<optimized out>, args=<optimized out>) at dl-error-skeleton.c:208
#22 0x00007ffff7d489f3 in __GI__dl_catch_error (objname=0x555555d6e010, errstring=0x555555d6e018, mallocedp=0x555555d6e008, operate=<optimized out>, args=<optimized out>) at dl-error-skeleton.c:227
#23 0x00007ffff76ebb59 in _dlerror_run (operate=operate@entry=0x7ffff76eb2f0 <dlopen_doit>, args=args@entry=0x7fffffffe170) at dlerror.c:170
#24 0x00007ffff76eb3da in __dlopen (file=<optimized out>, mode=<optimized out>) at dlopen.c:87
#25 0x00007ffff77554ee in llvm::sys::DynamicLibrary::getPermanentLibrary(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) () from /usr/local/lib/libomptarget.so.16git
#26 0x00007ffff77425f5 in RTLsTy::attemptLoadRTL(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, RTLInfoTy&) [clone .localalias] () from /usr/local/lib/libomptarget.so.16git
#27 0x00007ffff7742d43 in RTLsTy::loadRTLs() () from /usr/local/lib/libomptarget.so.16git
#28 0x00007ffff770b4df in __pthread_once_slow (once_control=0x555555d6c060, init_routine=0x7ffff7adbc20 <__once_proxy>) at pthread_once.c:116
#29 0x00007ffff7735dd5 in __tgt_register_lib () from /usr/local/lib/libomptarget.so.16git
#30 0x00007ffff7df006d in omp_offloading.descriptor_reg () from ./liba.so
#31 0x00007ffff7fe0b9a in call_init (l=<optimized out>, argc=argc@entry=1, argv=argv@entry=0x7fffffffe488, env=env@entry=0x7fffffffe498) at dl-init.c:72
#32 0x00007ffff7fe0ca1 in call_init (env=0x7fffffffe498, argv=0x7fffffffe488, argc=1, l=<optimized out>) at dl-init.c:30
#33 _dl_init (main_map=0x7ffff7ffe190, argc=1, argv=0x7fffffffe488, env=0x7fffffffe498) at dl-init.c:119
#34 0x00007ffff7fd013a in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#35 0x0000000000000001 in ?? ()
#36 0x00007fffffffe7a7 in ?? ()
#37 0x0000000000000000 in ?? ()
(gdb) thread 2
[Switching to thread 2 (Thread 0x7ffff7157700 (LWP 197306))]
#0  __lll_lock_wait (futex=futex@entry=0x7ffff7ffd968 <_rtld_global+2312>, private=0) at lowlevellock.c:52
52      in lowlevellock.c
(gdb) bt
#0  __lll_lock_wait (futex=futex@entry=0x7ffff7ffd968 <_rtld_global+2312>, private=0) at lowlevellock.c:52
#1  0x00007ffff7705131 in __GI___pthread_mutex_lock (mutex=0x7ffff7ffd968 <_rtld_global+2312>) at ../nptl/pthread_mutex_lock.c:115
#2  0x00007ffff7fe329b in tls_get_addr_tail (dtv=0x555555d7a9d0, the_map=0x7ffff7fc7000, ti=<optimized out>, ti=<optimized out>) at ../elf/dl-tls.c:761
#3  0x00007ffff7fe9dec in __tls_get_addr () at ../sysdeps/x86_64/tls_get_addr.S:55
#4  0x00007ffff7e0cc3d in tcmalloc::ThreadCache::CreateCacheIfNecessary() () from /usr/lib/x86_64-linux-gnu/libtcmalloc_minimal.so.4
#5  0x00007ffff7e12c85 in tcmalloc::allocate_full_cpp_throw_oom(unsigned long) () from /usr/lib/x86_64-linux-gnu/libtcmalloc_minimal.so.4
#6  0x00007ffff72a4abe in __gnu_cxx::new_allocator<hsa_signal_s>::allocate (this=0x555555dfe318, __n=4) at /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/ext/new_allocator.h:114
#7  std::allocator_traits<std::allocator<hsa_signal_s> >::allocate (__a=..., __n=4) at /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/alloc_traits.h:443
#8  std::_Vector_base<hsa_signal_s, std::allocator<hsa_signal_s> >::_M_allocate (this=0x555555dfe318, __n=4) at /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/stl_vector.h:343
#9  std::vector<hsa_signal_s, std::allocator<hsa_signal_s> >::_M_realloc_insert<hsa_signal_s const&> (this=0x555555dfe318, __position=..., __args=...) at /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/vector.tcc:440
#10 std::vector<hsa_signal_s, std::allocator<hsa_signal_s> >::push_back (this=0x555555dfe318, __x=...) at /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/stl_vector.h:1195
#11 rocr::core::Runtime::AsyncEvents::PushBack (this=this@entry=0x555555dfe318, signal=..., cond=HSA_SIGNAL_CONDITION_LT, value=0, handler=0x0, arg=0x0) at /workspaces/deps/ROCR-Runtime-rocm-5.4.1/src/core/runtime/runtime.cpp:1662
#12 0x00007ffff72a5534 in rocr::core::Runtime::AsyncEventsLoop () at /workspaces/deps/ROCR-Runtime-rocm-5.4.1/src/core/runtime/runtime.cpp:1140
#13 0x00007ffff72642d9 in rocr::os::ThreadTrampoline (arg=<optimized out>) at /workspaces/deps/ROCR-Runtime-rocm-5.4.1/src/core/util/lnx/os_linux.cpp:77
#14 0x00007ffff7702609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#15 0x00007ffff7d07133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) i threads
  Id   Target Id                                  Frame 
  1    Thread 0x7ffff76b6cc0 (LWP 197287) "a.out" __lll_lock_wait (futex=futex@entry=0x555555d83dd0, private=0) at lowlevellock.c:52
* 2    Thread 0x7ffff7157700 (LWP 197306) "a.out" __lll_lock_wait (futex=futex@entry=0x7ffff7ffd968 <_rtld_global+2312>, private=0) at lowlevellock.c:52
```

</details>

With this I'm fairly confident on what's happening. The application is deadlocked because Thread 1 is holding a lock with the address `0x7ffff7ffd968` and wants to lock `0x555555d83dd0` while thread 2 is holding `0x555555d83dd0` and would like to lock `0x7ffff7ffd968`.

- `0x555555d83dd0` is [rocr::core::Runtime::async_events_control_::lock](https://github.com/RadeonOpenCompute/ROCR-Runtime/blob/a0d5e18e7752563daf4da970eae5ac8b6056a4c0/src/core/inc/runtime.h#L398).
- `0x7ffff7ffd968` is locked by `dlopen` (The omp runtime has dynamically loaded ROCr) and attempted to be locked by `__tls_get_addr` (loading the thread local address of a variable) and seems to be a lock around the symbol table of the process in glibc.

[This >10 year old issue](https://bugzilla.redhat.com/show_bug.cgi?id=661676) describes the situation rocr is in very well: the thread that it spawns is waiting for the mutex that is held by `dlopen` while the initial thread is waiting for a mutex held by the second thread.

# Possible solution

One solution would be to delay spawning the second thread as late as possible so that no locks that it would be locking are waited by the initial thread during library initialization.

**Comment by dayatsin-amd** [comment]
We are currently looking into this

**Comment by dayatsin-amd** [comment]
We have a patch that fixed this. Will be part of 5.5 release

**Comment by jlgreathouse** [comment]
Hi @Maetveis  with the release of ROCm 5.5, did you find that your issue was addressed? Thanks.

**Comment by Maetveis** [comment]
> Hi @Maetveis with the release of ROCm 5.5, did you find that your issue was addressed? Thanks.

The reproducer no longer seems to hang. I'm no longer on the OpenMP offloaded application that initially triggered this, so I'll resolve.
