### ISSUE TITLE
Assertion with -D_GLIBCXX_ASSERTIONS

### ISSUE THREAD

**Issue by aquad** [RadeonOpenCompute/ROCR-Runtime#153]
Arch Linux packaging has a default `CXXFLAGS` entry: `-Wp,-D_GLIBCXX_ASSERTIONS`, which results in a runtime assertion with the following stacktrace:

```stacktrace
#4  0x00007fffc2cd30a2 in std::__glibcxx_assert_fail(char const*, int, char const*, char const*)
    (file=file@entry=0x7fffb24ea548 "/usr/include/c++/12.2.1/bits/stl_vector.h", line=line@entry=1123, function=function@entry=0x7fffb24f52d0 "std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = const char*; _Alloc = std::allocator<const char*>; reference = const char*&; size_type = long unsigned i"..., condition=condition@entry=0x7fffb24ea3d8 "__n < this->size()")
    at /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++11/debug.cc:60
#5  0x00007fffb246c875 in std::vector<char const*, std::allocator<char const*> >::operator[](unsigned long) (this=0x7fffffffc530, __n=0)
    at /usr/include/c++/12.2.1/bits/stl_vector.h:1121
#6  std::vector<char const*, std::allocator<char const*> >::operator[](unsigned long)
    (__n=0, this=0x7fffffffc530) at /usr/include/c++/12.2.1/bits/stl_vector.h:1121
#7  rocr::core::Runtime::LoadTools() (this=<optimized out>)
    at /usr/src/debug/hsa-rocr/ROCR-Runtime-rocm-5.4.2/src/core/runtime/runtime.cpp:1595
#8  0x00007fffb246cce8 in rocr::core::Runtime::Load() (this=0x55555af360c0)
    at /usr/src/debug/hsa-rocr/ROCR-Runtime-rocm-5.4.2/src/core/runtime/runtime.cpp:1386
#9  0x00007fffb246ce7c in rocr::core::Runtime::Acquire() ()
    at /usr/src/debug/hsa-rocr/ROCR-Runtime-rocm-5.4.2/src/core/runtime/runtime.cpp:112
#10 0x00007fffb244d46f in rocr::HSA::hsa_init() ()
    at /usr/src/debug/hsa-rocr/ROCR-Runtime-rocm-5.4.2/src/core/runtime/hsa.cpp:206
```

While I can just disable that build flag, the code could also avoid the assertion:

```diff
diff -aur a/src/core/runtime/runtime.cpp b/src/core/runtime/runtime.cpp
--- a/src/core/runtime/runtime.cpp	2022-12-14 22:47:12.000000000 +0800
+++ b/src/core/runtime/runtime.cpp	2023-01-29 09:53:55.084690262 +0800
@@ -1592,7 +1592,7 @@
       }
       if (!ld(&hsa_api_table_.hsa_api,
         hsa_api_table_.hsa_api.version.major_id,
-        failed.size(), &failed[0])) {
+        failed.size(), failed.data())) {
           failed.push_back(lib.name_.c_str());
           os::CloseLib(tool);
           continue;
```

**Comment by jellersby** [comment]
Related:

https://github.com/orgs/rocm-arch/discussions/937#discussioncomment-4733911

https://github.com/arch4edu/arch4edu/issues/203

**Comment by dayatsin-amd** [comment]
Thank you for the patch. Changes will be in 5.6 release
